=== AdemolaAdigun/A-Simple-Football-League-Table/football-api/Client/xsd/schema1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
       <xs:element name="matches">
              <xs:complexType>
                     <xs:sequence>
                            <xs:element name="matches" maxOccurs="unbounded">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="MatchID" type="xs:int"></xs:element>
                                                 <xs:element name="TeamHomeID" type="xs:int"></xs:element>
                                                 <xs:element name="TeamHomeFormation" type="xs:int"></xs:element>
                                                 <xs:element name="ResultOfTeamHome" type="xs:int"></xs:element>
                                                 <xs:element name="TeamID" type="xs:int"></xs:element>
                                                 <xs:element name="TeamName" type="xs:string"></xs:element>
                                             </xs:sequence>
                                      </xs:complexType>
                               </xs:element>
                        </xs:sequence>
                 </xs:complexType>
          </xs:element>
</xs:schema>

=== AdemolaAdigun/A-Simple-Football-League-Table/football-api/Client/xsd/matchesXML.xml
<?xml version='1.0'?>
<matches xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema1.xsd">
	<matches>
		<MatchID>1</MatchID>
		<TeamHomeID>1</TeamHomeID>
		<TeamHomeFormation>433</TeamHomeFormation>
		<ResultOfTeamHome>3</ResultOfTeamHome>
		<TeamID>1</TeamID>
		<TeamName>RealMadrid</TeamName>
	</matches>
	<matches>
		<MatchID>7</MatchID>
		<TeamHomeID>1</TeamHomeID>
		<TeamHomeFormation>4231</TeamHomeFormation>
		<ResultOfTeamHome>3</ResultOfTeamHome>
		<TeamID>1</TeamID>
		<TeamName>RealMadrid</TeamName>
	</matches>
	<matches>
		<MatchID>1</MatchID>
		<TeamHomeID>2</TeamHomeID>
		<TeamHomeFormation>433</TeamHomeFormation>
		<ResultOfTeamHome>1</ResultOfTeamHome>
		<TeamID>2</TeamID>
		<TeamName>Barcelona</TeamName>
	</matches>
	<matches>
		<MatchID>7</MatchID>
		<TeamHomeID>2</TeamHomeID>
		<TeamHomeFormation>442</TeamHomeFormation>
		<ResultOfTeamHome>1</ResultOfTeamHome>
		<TeamID>2</TeamID>
		<TeamName>Barcelona</TeamName>
	</matches>
	<matches>
		<MatchID>2</MatchID>
		<TeamHomeID>3</TeamHomeID>
		<TeamHomeFormation>4231</TeamHomeFormation>
		<ResultOfTeamHome>6</ResultOfTeamHome>
		<TeamID>3</TeamID>
		<TeamName>ManchesterCity</TeamName>
	</matches>
	<matches>
		<MatchID>6</MatchID>
		<TeamHomeID>3</TeamHomeID>
		<TeamHomeFormation>433</TeamHomeFormation>
		<ResultOfTeamHome>6</ResultOfTeamHome>
		<TeamID>3</TeamID>
		<TeamName>ManchesterCity</TeamName>
	</matches>
	<matches>
		<MatchID>2</MatchID>
		<TeamHomeID>4</TeamHomeID>
		<TeamHomeFormation>442</TeamHomeFormation>
		<ResultOfTeamHome>3</ResultOfTeamHome>
		<TeamID>4</TeamID>
		<TeamName>Arsenal</TeamName>
	</matches>
	<matches>
		<MatchID>6</MatchID>
		<TeamHomeID>4</TeamHomeID>
		<TeamHomeFormation>433</TeamHomeFormation>
		<ResultOfTeamHome>3</ResultOfTeamHome>
		<TeamID>4</TeamID>
		<TeamName>Arsenal</TeamName>
	</matches>
	<matches>
		<MatchID>3</MatchID>
		<TeamHomeID>5</TeamHomeID>
		<TeamHomeFormation>442</TeamHomeFormation>
		<ResultOfTeamHome>3</ResultOfTeamHome>
		<TeamID>5</TeamID>
		<TeamName>Liverpool</TeamName>
	</matches>
	<matches>
		<MatchID>8</MatchID>
		<TeamHomeID>5</TeamHomeID>
		<TeamHomeFormation>442</TeamHomeFormation>
		<ResultOfTeamHome>3</ResultOfTeamHome>
		<TeamID>5</TeamID>
		<TeamName>Liverpool</TeamName>
	</matches>
	<matches>
		<MatchID>3</MatchID>
		<TeamHomeID>6</TeamHomeID>
		<TeamHomeFormation>433</TeamHomeFormation>
		<ResultOfTeamHome>1</ResultOfTeamHome>
		<TeamID>6</TeamID>
		<TeamName>Tottenham</TeamName>
	</matches>
	<matches>
		<MatchID>8</MatchID>
		<TeamHomeID>6</TeamHomeID>
		<TeamHomeFormation>433</TeamHomeFormation>
		<ResultOfTeamHome>1</ResultOfTeamHome>
		<TeamID>6</TeamID>
		<TeamName>Tottenham</TeamName>
	</matches>
</matches>
