=== AdemolaAdigun/A-Simple-Football-League-Table/football-api/Client/xsd/schema2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
       <xs:element name="team">
              <xs:complexType>
                     <xs:sequence>
                            <xs:element name="team" maxOccurs="unbounded">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="Name" type="xs:string"></xs:element>
                                                 <xs:element name="Goals" type="xs:int"></xs:element>
                                                 <xs:element name="Shots" type="xs:int"></xs:element>
                                                 <xs:element name="ShotsOnTarget" type="xs:int"></xs:element>
                                                 <xs:element name="Fouls" type="xs:int"></xs:element>
                                                 <xs:element name="YellowCards" type="xs:int"></xs:element>
                                                 <xs:element name="RedCards" type="xs:int"></xs:element>
                                                 <xs:element name="Passes" type="xs:int"></xs:element>
                                                 <xs:element name="Dribbles" type="xs:int"></xs:element>
                                                 <xs:element name="Tackles" type="xs:int"></xs:element>
                                                 <xs:element name="Saves" type="xs:int"></xs:element>
                                             </xs:sequence>
                                      </xs:complexType>
                               </xs:element>
                        </xs:sequence>
                 </xs:complexType>
          </xs:element>
   </xs:schema>

=== AdemolaAdigun/A-Simple-Football-League-Table/football-api/Client/xsd/teamsXML.xml
<?xml version='1.0'?>
<team xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema2.xsd">
	<team>
		<Name>EDERSON</Name>
		<Goals>0</Goals>
		<Shots>0</Shots>
		<ShotsOnTarget>0</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>0</Passes>
		<Dribbles>0</Dribbles>
		<Tackles>0</Tackles>
		<Saves>10</Saves>
	</team>
	<team>
		<Name>WALKER</Name>
		<Goals>0</Goals>
		<Shots>3</Shots>
		<ShotsOnTarget>1</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>21</Passes>
		<Dribbles>9</Dribbles>
		<Tackles>4</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>MENDY</Name>
		<Goals>0</Goals>
		<Shots>0</Shots>
		<ShotsOnTarget>0</ShotsOnTarget>
		<Fouls>1</Fouls>
		<YellowCards>1</YellowCards>
		<RedCards>0</RedCards>
		<Passes>12</Passes>
		<Dribbles>2</Dribbles>
		<Tackles>2</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>STONES</Name>
		<Goals>0</Goals>
		<Shots>0</Shots>
		<ShotsOnTarget>0</ShotsOnTarget>
		<Fouls>2</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>11</Passes>
		<Dribbles>2</Dribbles>
		<Tackles>2</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>LAPORTE</Name>
		<Goals>0</Goals>
		<Shots>2</Shots>
		<ShotsOnTarget>1</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>14</Passes>
		<Dribbles>3</Dribbles>
		<Tackles>3</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>WALKER</Name>
		<Goals>1</Goals>
		<Shots>4</Shots>
		<ShotsOnTarget>3</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>22</Passes>
		<Dribbles>8</Dribbles>
		<Tackles>1</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>FERNANDINHO</Name>
		<Goals>0</Goals>
		<Shots>3</Shots>
		<ShotsOnTarget>1</ShotsOnTarget>
		<Fouls>1</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>20</Passes>
		<Dribbles>10</Dribbles>
		<Tackles>1</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>SILVA</Name>
		<Goals>0</Goals>
		<Shots>3</Shots>
		<ShotsOnTarget>3</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>18</Passes>
		<Dribbles>12</Dribbles>
		<Tackles>0</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>DE BRUYNE</Name>
		<Goals>1</Goals>
		<Shots>4</Shots>
		<ShotsOnTarget>3</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>11</Passes>
		<Dribbles>2</Dribbles>
		<Tackles>0</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>SANE</Name>
		<Goals>1</Goals>
		<Shots>4</Shots>
		<ShotsOnTarget>3</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>28</Passes>
		<Dribbles>10</Dribbles>
		<Tackles>1</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>AGUERO</Name>
		<Goals>0</Goals>
		<Shots>2</Shots>
		<ShotsOnTarget>2</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>19</Passes>
		<Dribbles>10</Dribbles>
		<Tackles>0</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>EDERSON</Name>
		<Goals>0</Goals>
		<Shots>0</Shots>
		<ShotsOnTarget>0</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>0</Passes>
		<Dribbles>0</Dribbles>
		<Tackles>0</Tackles>
		<Saves>10</Saves>
	</team>
	<team>
		<Name>WALKER</Name>
		<Goals>0</Goals>
		<Shots>3</Shots>
		<ShotsOnTarget>1</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>21</Passes>
		<Dribbles>9</Dribbles>
		<Tackles>4</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>MENDY</Name>
		<Goals>0</Goals>
		<Shots>0</Shots>
		<ShotsOnTarget>0</ShotsOnTarget>
		<Fouls>1</Fouls>
		<YellowCards>1</YellowCards>
		<RedCards>0</RedCards>
		<Passes>12</Passes>
		<Dribbles>2</Dribbles>
		<Tackles>2</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>STONES</Name>
		<Goals>0</Goals>
		<Shots>0</Shots>
		<ShotsOnTarget>0</ShotsOnTarget>
		<Fouls>2</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>11</Passes>
		<Dribbles>2</Dribbles>
		<Tackles>2</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>LAPORTE</Name>
		<Goals>0</Goals>
		<Shots>2</Shots>
		<ShotsOnTarget>1</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>14</Passes>
		<Dribbles>3</Dribbles>
		<Tackles>3</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>WALKER</Name>
		<Goals>1</Goals>
		<Shots>4</Shots>
		<ShotsOnTarget>3</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>22</Passes>
		<Dribbles>8</Dribbles>
		<Tackles>1</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>FERNANDINHO</Name>
		<Goals>0</Goals>
		<Shots>3</Shots>
		<ShotsOnTarget>1</ShotsOnTarget>
		<Fouls>1</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>20</Passes>
		<Dribbles>10</Dribbles>
		<Tackles>1</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>SILVA</Name>
		<Goals>0</Goals>
		<Shots>3</Shots>
		<ShotsOnTarget>3</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>18</Passes>
		<Dribbles>12</Dribbles>
		<Tackles>0</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>DE BRUYNE</Name>
		<Goals>1</Goals>
		<Shots>4</Shots>
		<ShotsOnTarget>3</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>11</Passes>
		<Dribbles>2</Dribbles>
		<Tackles>0</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>SANE</Name>
		<Goals>1</Goals>
		<Shots>4</Shots>
		<ShotsOnTarget>3</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>28</Passes>
		<Dribbles>10</Dribbles>
		<Tackles>1</Tackles>
		<Saves>0</Saves>
	</team>
	<team>
		<Name>AGUERO</Name>
		<Goals>0</Goals>
		<Shots>2</Shots>
		<ShotsOnTarget>2</ShotsOnTarget>
		<Fouls>0</Fouls>
		<YellowCards>0</YellowCards>
		<RedCards>0</RedCards>
		<Passes>19</Passes>
		<Dribbles>10</Dribbles>
		<Tackles>0</Tackles>
		<Saves>0</Saves>
	</team>
</team>
